<?php

namespace ConcoursBundle\Repository;

/**
 * CompetitionWineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionWineRepository extends \Doctrine\ORM\EntityRepository
{
}
