<?php

namespace ConcoursBundle\Repository;

/**
 * MedalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedalRepository extends \Doctrine\ORM\EntityRepository
{
}
