<?php

namespace AppBundle\Repository;

/**
 * NewsAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
