product_product_conditioning:
    resource: "@ProductBundle/Controller/ProductConditioningController.php"
    type:     annotation

app_news:
    resource: "@AppBundle/Controller/NewsController.php"
    type:     annotation

product_purchase:
    resource: "@ProductBundle/Controller/PurchaseController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

media_files:
    resource: "@MediaBundle/Controller/FilesController.php"
    type:     annotation

cart:
    resource: "@UserBundle/Controller/CartController.php"
    type:     annotation

product_universe:
    resource: "@ProductBundle/Controller/UniverseController.php"
    type:     annotation


product_purchase:
    resource: "@ProductBundle/Controller/PurchaseController.php"
    type:     annotation

concours:
    resource: "@ConcoursBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/concours


contract:
    resource: "@ContractBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/contract

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/user

user_consumer:
    resource: "@UserBundle/Controller/UserConsumerController.php"
    type:     annotation

media:
    resource: "@MediaBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/media

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/product

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_contact:
    resource: "@AppBundle/Controller/ContactController.php"
    type:     annotation

profil:
    resource: "@UserBundle/Controller/ProfileCommandController.php"
    type:     annotation

profil_products:
    resource: "@UserBundle/Controller/ProfileCommandController.php"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register_fos

