fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

product_universe:
    resource: "@ProductBundle/Controller/UniverseController.php"
    type:     annotation

product_wine:
    resource: "@ProductBundle/Controller/WineController.php"
    type:     annotation

concours:
    resource: "@ConcoursBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/concours

contract:
    resource: "@ContractBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/contract

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/user

media:
    resource: "@MediaBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/media

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/product

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register_fos

