<?php

namespace UserBundle\Repository;

/**
 * ProducerStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
