<?php

namespace UserBundle\Repository;

/**
 * UserProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
