<?php

namespace UserBundle\Repository;

/**
 * UserMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function UserMediaEnabled($limit)
    {
        return $this->createQueryBuilder('m')
            ->where("m.enabled = TRUE")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function UserMediaDisabled($limit)
    {
        return $this->createQueryBuilder('m')
            ->where("m.enabled = FALSE")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
