<?php

namespace UserBundle\Repository;

/**
 * UserProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProducerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProducer($limit, $offset)
    {
        return $this->createQueryBuilder('m')
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getQuery()
            ->getResult();
    }
}
