<?php

namespace UserBundle\Repository;

/**
 * UserConsumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConsumerRepository extends \Doctrine\ORM\EntityRepository
{
}
