<?php

namespace UserBundle\Repository;

/**
 * UserMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
