services:
#    product.example:
#        class: ProductBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  product_stock_update:
      class:   ProductBundle\ProductStockUpdate\ProductStockUpdate
      arguments: ["@service_container"]
      tags:
          - { name: doctrine.event_subscriber }
