<?php

namespace ContractBundle\Repository;

/**
 * OptionSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
