<?php

namespace ContractBundle\Repository;

/**
 * OptionSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOptionSubscriptionsBetweenTwoDates(\DateTime $beginDate, \DateTime $endDate, $limit, $offset)
    {
        return $this->createQueryBuilder('m')
            ->where("m.dateSubscription > ?1")
            ->andWhere("m.dateSubscription < ?2")
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter(1, $beginDate)
            ->setParameter(2, $endDate)
            ->getQuery()
            ->getResult();
    }

    public function findOptionSubscriptionsAfterADate(\DateTime $beginDate, $limit, $offset)
    {
        return $this->createQueryBuilder('m')
            ->where("m.dateSubscription > ?1")
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter(1, $beginDate)
            ->getQuery()
            ->getResult();
    }
}
