<?php

namespace MediaBundle\Repository;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMediasBetweenTwoDates(\DateTime $beginDate, \DateTime $endDate, $limit, $offset)
    {
        return $this->createQueryBuilder('m')
            ->where("m.date > ?1")
            ->andWhere("m.date < ?2")
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter(1, $beginDate)
            ->setParameter(2, $endDate)
            ->getQuery()
            ->getResult();
    }

    public function findMediasAfterADate(\DateTime $date, $limit, $offset)
    {
        return $this->createQueryBuilder('m')
            ->where("m.date > ?1")
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter(1, $date)
            ->getQuery()
            ->getResult();
    }
}
