<?php

namespace ProductBundle\Repository;

/**
 * ConditioningTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditioningTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
