<?php

namespace ProductBundle\Repository;

/**
 * GrapeVarietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrapeVarietyRepository extends \Doctrine\ORM\EntityRepository
{
}
