<?php

namespace ProductBundle\Repository;

/**
 * PictureProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureProductRepository extends \Doctrine\ORM\EntityRepository
{
}
