<?php

namespace ProductBundle\Repository;

/**
 * PictureUniverseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureUniverseRepository extends \Doctrine\ORM\EntityRepository
{
}
