<?php

namespace ProductBundle\Repository;

/**
 * ProductConditioningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductConditioningRepository extends \Doctrine\ORM\EntityRepository
{
}
