<?php

namespace ProductBundle\Repository;

/**
 * ProductConditioningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductConditioningRepository extends \Doctrine\ORM\EntityRepository
{


    public function findProductConditionningByPrice($price)
    {

        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where($queryBuilder->expr()->lte('p.pubPrice', $price));
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

   public function getMaxConditionningPrice()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->select('MAX(p.pubPrice)');
        $query = $queryBuilder->getQuery();
        return $query->getSingleScalarResult();
    }






}

