<?php

namespace ProductBundle\Repository;

/**
 * ProductEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
