<?php

namespace ProductBundle\Repository;

/**
 * ProductPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
