<?php

namespace ProductBundle\Repository;

/**
 * SpiritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpiritRepository extends \Doctrine\ORM\EntityRepository
{
}
