<?php

namespace ProductBundle\Repository;

/**
 * UniverseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniverseRepository extends \Doctrine\ORM\EntityRepository
{

}


