<?php

namespace ProductBundle\Repository;

/**
 * UniverseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniverseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProductsByName($name)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $toto = '%vodka%';
        $queryBuilder->where($queryBuilder->expr()->like('p.name', $toto))
            ->setParameter('name', '%'.$name.'%');

        $query = $queryBuilder->getQuery();
        return $query->getResult();

    }









}


