<?php

namespace ProductBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends EntityRepository
{

    public function getColors()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->select('p.color')->distinct(true);
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function findProductConditionningByColor($color)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.color = :color')
        ->setParameter('color', $color);
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }


}
