<?php

namespace ProductBundle\Repository;
use Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\QueryBuilder;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends EntityRepository
{

    public function findRegionName(){

        $qb = $em->getRepository("GerlaFrontendBundle:Store")->createQueryBuilder("p");

        $province = $qb->select("p")
            ->distinct(true)
            ->getQuery()
            ->getResult();

    }


}
